### ISSUE TITLE
Discord does not restore.

### ISSUE THREAD

**Issue by Aeswere** [Todd1561/TANWindowMgr#1]
Basically the title.

I am using BetterDiscord with a theme, if that info is helpful.

Link if needed: https://github.com/rauenzi/BetterDiscordApp

&nbsp;
Edit: So I did a reboot for unrelated reasons, and I've found that it does restore the window, but not to how I had it set. And the window will not go in front of my Spotify window at all.

Edit after trying while making my first edit: so my settings file has 
```
Discord,0,0,0,0,0
Spotify,1923,130,1030,3523,1
```
in it after saving them just now. I would manually type the numbers in to see if that makes it work but I don't know how to get the x and y positions to even do that.

**Comment by Todd1561** [comment]
I've fixed an issue where the Window Manager couldn't select the proper process ID in cases where a program you're trying to save/reposition has spawned multiple threads.  I suspect that's what is going on here.  I don't have all of this Discord stuff setup on my computer, so if you can please test out the latest release and see if it helps at all.

You can get the latest release here: https://github.com/Todd1561/TANWindowMgr/releases/tag/1.1

**Comment by Aeswere** [comment]
It seems to work now.
