### ISSUE TITLE
Add 'Window Sets' feature

### ISSUE THREAD

**Issue by postiffm** [Todd1561/TANWindowMgr#10]
I want to try this app to manage my 4K 43" monitor. Windows are all over the place and I need some help :-)

So, how do I begin? Could you add to the README.md a section of instructions on how to get started--what software, how to build? 

Thank you. I don't want to be a bother with this simplistic-seeming question, but I've not done anything in VB except for a few macros inside MS Word.

**Comment by Todd1561** [comment]
Hey there's no need to know anything about coding or compiling.  I already have pre-compiled binaries on the releases page, just download and run. https://github.com/Todd1561/TANWindowMgr/releases 

Just follow the instructions in the readme, which is basically just save the downloaded EXE someplace on your computer.  Add a shortcut to the program to your Windows 'Startup' folder if you want the program to run at each boot, which I'd recommend.

**Comment by postiffm** [comment]
OK, I see it now. Thanks, I am trying it right now and I think it will be very helpful. I wonder how hard would it be to add "window sets" so that I could restore one set and "bring to front" for one type of task I do; then when I want to switch to my "communications" task, I could restore another set of windows and bring them to the front.

**Comment by Todd1561** [comment]
Interesting idea, I've flagged this issue as a feature request now.  I can't promise I'll be able to tackle this anytime soon, but I'll report back here if I do.

**Comment by postiffm** [comment]
One way to implement this that I'm thinking about: instead of having settings.ini, have settings.tan or settings.twm (although that extension is used for "theWord" modules, I think). Associate that file type with your app. Opening that file would launch TANWindowMgr (or talk to the existing running instance) and have it restore those windows specified in the .tan file. The user could then create any number of profile files for the different window sets/groups I want. An option could be somehow added to TANWindowMgr to open/save the desired window set.

Or, all window sets could be specified in the same settings.ini file. I'm not sure which is easier, or if one or the other approach would a little easier to use.

**Comment by Todd1561** [comment]
This is basically the concept of 'profiles' which I've considered adding in but I personally have had no need for it and no one has asked that I can remember.  But I found some time this weekend to release version 1.3 that has this feature.  You can now create as many layout profiles as you wish using the 'Manage Profiles' option in the tray menu.  Each time you add a new profile a corresponding 'Load Profile' option will be added to the tray menu.  This is backwards compatible with the old format of the Settings.ini file by placing any saved layouts that don't have a profile specified in the 'Default' profile.  You can also use the now extended `-restore=<Name>` command line argument to restore these profiles.

Let me know how it works for you.  Enjoy!

https://github.com/Todd1561/TANWindowMgr/releases/tag/1.3

**Comment by postiffm** [comment]
I would say version 1.3 closes this enhancement request. I have tested it and it is pretty much exactly what I was hoping for. I did notice that one window would restore for a second and then bounce back to minimized state. When I tweaked the position of the window and re-saved the profile, it behaved as expected.

One small thing: it would be nice if the "Manage Profile" window would not automatically disappear when you save a profile. I had in my mind the use case when I get a new monitor setup and want to "fix up" all my profiles at once, without having to go back to the profile manager to change each one. That is a nit pick relative to what this can now do. Awesome, and thanks Todd!

**Comment by Todd1561** [comment]
Glad this works well for you.  I agree, auto-closing the Manage Profiles window doesn't really make sense now that it does multiple profiles.  So I just introduced that change in the latest 1.31 release https://github.com/Todd1561/TANWindowMgr/releases/tag/1.31
