### ISSUE TITLE
unfamiliar with git

### ISSUE THREAD

**Issue by BobRichmond** [Todd1561/TANWindowMgr#11]
This program sounds just like what I need to reopen, size, and reposition the 4 programs I always have running on my second (extended) monitor after a restart or shutdown. However since I am unfamiliar with Git I do not know what to download and how to install it on a fully updated Windows 10 pro computer. Could you help me with this?

Thanks for your time in helping me with this problem.

**Comment by Todd1561** [comment]
I already provide pre-compiled binaries on the released page, just download the EXE and save it to your computer.  Follow the steps on the main readme page

https://github.com/Todd1561/TANWindowMgr/releases
