### ISSUE TITLE
App doen't see Windows Explorer windows

### ISSUE THREAD

**Issue by Zoli1972** [Todd1561/TANWindowMgr#20]
Hi,

the app doesn't see Explorer windows and doesn't display them in the list.

Zoli

**Comment by HansdBr** [comment]
Has anyone already found a solution for problem with Explorer. I don't see a way to include Explorer window in profile?

**Comment by Todd1561** [comment]
This is basically the same as this issue so I'm closing as a duplicate: https://github.com/Todd1561/TANWindowMgr/issues/2

TANWindowMgr identifies applications by their process name (e.g. notepad.exe).  The problem with Windows Explorer windows is they are just part of the main "explorer.exe" program that is the entire underlying UI for Windows so they can't be identified properly.  A different method for identifying windows would need to be developed, maybe one day...
