### ISSUE TITLE
Feature Request: "Save All" window positions

### ISSUE THREAD

**Issue by yz778** [Todd1561/TANWindowMgr#3]
Add option to quickly save all window positions.

Example:
![image](https://user-images.githubusercontent.com/2322981/85227817-6dfc3b80-b394-11ea-9f6d-26171b31dbbe.png)

**Comment by Todd1561** [comment]
I've added the functionality in the latest [1.2 release](https://github.com/Todd1561/TANWindowMgr/releases/tag/1.2)
