### ISSUE TITLE
Feature Request: CLI options

### ISSUE THREAD

**Issue by yz778** [Todd1561/TANWindowMgr#4]
Add CLI options to Save and Restore

Example:
TANWindowMgr.exe -save preset1
TANWindowMgr.exe -restore preset1

Reason:
Makes it really easy to have a batch file/powershell script to launch a set of apps and use TAN to snap windows into position.

**Comment by Todd1561** [comment]
I've added this functionality in the latest [1.2 release.](https://github.com/Todd1561/TANWindowMgr/releases/tag/1.2)  Details can be found in the readme.

Your syntax seems to suggest the ability to save different profiles.  This isn't in the scope of the project at the moment, but I can consider that if there's interest.  For now you can save all detected windows, restore from the config file and optionally exit TANWindowMgr after loading the program.  The last option should be useful in your scripting example where I don't imagine you'd want to leave the program running in the tray.  If you do you can omit that switch.

**Comment by yz778** [comment]
This is perfect thank you!

My use case for this: I have a triple monitor setup and each time my computer [goes to sleep / resume the windows are re-positioned away from my main monitor.](https://superuser.com/questions/453446/how-can-i-stop-windows-re-positioning-after-waking-from-sleep) I have to then re-arrange everything each time. Your tool, and now with the CLI options solved the problem!

I will now investigate options for automatically calling this on entering sleep and resuming from sleep through Task Scheduler.
