### ISSUE TITLE
Applications with Same Name Don't Save/Restore Properly

### ISSUE THREAD

**Issue by RobR62** [Todd1561/TANWindowMgr#6]
Both Microsoft OneNote (Windows 10 version) and Microsoft To Do show up as "ApplicationFrameHost" when trying to save, so they don't save independently and restore properly. Thanks for this great app -- I use it constantly!

**Comment by Todd1561** [comment]
Thanks! Glad you're getting some use out of it.  I've noticed that issue with other MS apps as well, been meaning to dig into it more to see if there's a workaround.  If I can find anything I'll report back here.

**Comment by Todd1561** [comment]
Moving this to the more specific issue https://github.com/Todd1561/TANWindowMgr/issues/14
