### ISSUE TITLE
Compiled .exe?

### ISSUE THREAD

**Issue by Cra7y** [Todd1561/TANWindowMgr#8]
Hey, sounds like this is just the program I need!
However, do you host a compiled version anywhere?

**Comment by Cra7y** [comment]
Well i'm an idiot, missed the realese, don't know what i was thinking...

**Comment by Todd1561** [comment]
Yep it's in the releases section: https://github.com/Todd1561/TANWindowMgr/releases/tag/1.2

**Comment by Todd1561** [comment]
Ha no worries.  I hope the program works well for you.

**Comment by Cra7y** [comment]
Hehe, thanks for the fast reply ;)
Just tested it, does it have known issues with windows pinned to the corners of the screen (using windows build in snapping tools)

**Comment by Cra7y** [comment]
It fixed it to use FanzyZones in PowerToys to arrange them (which actually resizes the windows), so i guess it's a separate issue. I will create that now.

**Comment by Todd1561** [comment]
I'm not familiar with FranzyZones, but yes there does seem to be an issue when windows are snapped using the native feature of Windows 10.  I'll have to look into that more.  For now if you manually place the windows where you want them you should be good.

**Comment by Cra7y** [comment]
FancyZones is just an alternative to the native feature offering more control and custom snapping zones. But contrary to the native feature it actually resizes windows when sapping them
